### ISSUE TITLE
how to enable modern auth

### ISSUE THREAD

**Issue by matthewaceware** [DougHennig/SFMail#1]
First of all, I want to say that this is working great against a Basic Authentication email server. I had my email administrator disable Basic Authentication and now I am getting this error from the server:

> OLE IDispatch exception code 0 from MailKit: 535: 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [SA0PR11CA0015.namprd11.prod.outlook.com]

I think I just don't have it set up correctly to send emails using a Modern Authentication. Can someone please provide an example of how this would work and any additional configuration that would need done?

Much appreciated!

Best,
Matthew

**Comment by DougHennig** [comment]
Try changing the nSecurityOptions property (see the notes in README). If that doesn't take care of it, then what type of authentication is your server using?

**Comment by matthewaceware** [comment]
I was leaving nSecurityOptions on 1 (Auto). If I set it to 2, I got a big, general error on enabling TLS. Figured out that I need to use port 465, but am now getting a timeout.  Not sure what is going on there.

My network admin is asking about the authorization token. I see nothing about that in the readme. How do I hook into the Application ID and Object ID set up on the Azure Active Directory admin center for a new Enterprise Application? (Note: I have no idea what I'm talking about, so I hope you understand what I'm trying to say. Give me a call if you need more information and I'll get my network admin on the phone, too.)

**Comment by DougHennig** [comment]
Since SFMail is just a wrapper for MailKit (https://github.com/jstedfast/MailKit), which is itself a wrapper for MimeKit (https://github.com/jstedfast/MimeKit), I suggest checking the documentation of those projects to see how this is supported. I don't know anything about authorization beyond basic.

**Comment by matthewaceware** [comment]
After much research, many trials, and almost as many errors, I've figured this out and am providing my solution here to help guide future visitors (as this will be huge here closer to the end of the year when Microshaft shuts down Basic Auth). To get an authentication from Microsoft, you must get an App registration with SMTP.Send permissions granted from Microsoft Graft. Then you must get a token by doing:
`			IF EMPTY(xs_emtenant)
				lcHTML=''
			ELSE
				IF ATC([WWHTTP],SET("Classlib")) = 0
					SET PROCEDURE TO wwhttp additive
				ENDIF
				IF ATC([WWUTILS],SET("Classlib")) = 0
					SET PROCEDURE TO wwutils additive
				ENDIF
				loHTTP=CREATEOBJECT("wwHttp")
				loHTTP.addpostkey("client_id",xs_emclient)
				loHTTP.addpostkey("grant_type","password")
				loHTTP.addpostkey("username",xs_emusername)
				loHTTP.addpostkey("password",xs_empassword)
				loHTTP.addpostkey("scope",xs_emscope)
				loHTTP.addpostkey("client_secret",xs_emsecret)
				lcHTML=loHTTP.HTTPGet(xs_emtenant)
				IF "error"$lcHTML
					RETURN lcHTML
				ENDIF
			ENDIF`
I created a new procedure in sfmail and call it with:
`				IF !EMPTY(lcHTML)
					.oAuthenticate=.MKSaslMechanismOAuth2(ALLTRIM(xs_emusername),STREXTRACT(lcHTML,["],["],15))
				ENDIF`
New procedure:
`*==============================================================================
* Method:			MKSaslMechanismOAuth2
* Purpose:			Gets the OAuth2 authentication key
* Author:			Matthew Olson
* Last revision:	03/01/2022
* Parameters:		UserID, AccessToken
* Returns:			character authentication key to pass to Authenticate()
*==============================================================================
		
	PROCEDURE MKSaslMechanismOAuth2
		PARAMETERS pUserID,pAccessToken
		LOCAL loBridge,loOAuth
	* Get an instance of wwDotNetBridge and load the assembly.

		DO wwDotNetBridge
		loBridge = GetwwDotNetBridge()
		lcPath   = ''
		IF NOT FILE('MailKit.dll')
			lcPath = .GetAppFolder()
		ENDIF NOT FILE('MailKit.dll')
		loBridge.LoadAssembly(lcPath + 'MailKit.dll')

		IF EMPTY(loBridge.cErrorMsg)
			return loBridge.CreateInstance('MailKit.Security.SaslMechanismOAuth2',pUserID,pAccessToken)
		ELSE
			RETURN loBridge.cErrorMsg
		ENDIF
	ENDPROC`
This also means that I had to create a new property in SMTPLibrary2 and then use the token to Authenticate with instead of username and password:
`client.Authenticate(OAuthenticate);`

You're welcome.

**Comment by DougHennig** [comment]
Greatly appreciated, Matt. This may help with Gmail too since it's moving (or moved) away from basic authentication too.

**Comment by DougHennig** [comment]
It's not clear to me where you call the code you showed at the top of the message, or what changes you made to SMTPLibrary2. Can you show me a complete example of calling SFMail to send an email, plus the changes you made in SMTPLibrary2? Thanks.

**Comment by DougHennig** [comment]
According to https://support.google.com/cloud/answer/9110914, access to Gmail is considered to be a Restricted scope and requires undergoing an annual independent, third-party security assessment. That seems like a huge PITA. Did you have you had any luck with Gmail?

**Comment by matthewaceware** [comment]
Haven't really looked into it. Been fighting way too many fires this week. I might have time tomorrow to look at things, but the way this week has been going, next week is probably more likely.
