### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by wongdh** [DougHennig/SFMail#2]
Hi, i am able to send out email using one attachment, however when i try to attach more than one it will come out error
ole idispatch exception code 0 from mscorlib illegal characters in path

![image](https://user-images.githubusercontent.com/24403676/172765986-90521342-c7d6-4c4d-ad81-62c97f56ba1d.png)

my attachments string is like "c:\file1.pdf,c:\file2.pdf"
anyone can help?
thank you

**Comment by DougHennig** [comment]
What EXACTLY is the cAttachments property set to? "Illegal characters in the path" sounds like one or more of the paths you are specifying is invalid.

**Comment by wongdh** [comment]
similar to this. i checked and make sure all the files exists
 loMail.cAttachments = "d:\tmp\file1.pdf.d:\tmp\file2.pdf,d:\tmp\file3.pdf"

**Comment by DougHennig** [comment]
Perhaps I was not clear. What EXACTLY (not "similar to this" but exactly) is the cAttachments property set to?

**Comment by wongdh** [comment]
This is what i set to the property.

![Snipaste_2022-06-13_09-27-19](https://user-images.githubusercontent.com/24403676/173263766-3bea79dc-e1d1-490c-ba00-395d33df04e3.png)

please advice. thanks

**Comment by DougHennig** [comment]
I see a comma after the last file name. Try removing that to see if it helps.

**Comment by wongdh** [comment]
Hi. i removed the last comma, the error is the same

**Comment by DougHennig** [comment]
Isn't that statement more than 256 bytes long? What if you break it up like:

loMail.cAttachments = "first file" + ;
    "second file" + ;
    "third file" + ;
etc.

Even so, the issue is still there there are illegal characters in the paths you are specifying, so you will have to fix that.
