### ISSUE TITLE
Sending plaintext body as html removes line ending

### ISSUE THREAD

**Issue by kobruleht** [DougHennig/SFMail#4]
To reproduce, send plaintext message containing < and > characters like

```
Hello,

Is 

3<5 

or 

3>5 ?

```
SFMail sends this as html body.
In Thunderbird line endings are ignored. Received message appears in single line:

`Hello, Is  3<5  or  3>5 ?
`

Proposal:

UseHtml property should be set by caller. FoxPro class should contain this property.

Instead of 

`loMail.UseHtml         = '<' $ .cBody and '>' $ .cBody`

`loMail.UseHtml         = .cUseHtml `

should used.

**Comment by DougHennig** [comment]
Added lUseHTML in the latest build. It defaults to .F. but is automatically set to .T. if you set cBody to a value containing both "<" and ">". You can set it back to .F. if desired before calling Send.
