### ISSUE TITLE
Replace Mimekit and Mailkit assemblies with newer, make self contained

### ISSUE THREAD

**Issue by kobruleht** [DougHennig/SFMail#5]
Mimekit and Mailkit assemblies included are old.
There are lot of fixes and newer .NET versions are released.
.NET 6 allows to create self contained application which does not require framework to be installed.

.NET assemblies should replaced with latest ones. 
Package should be self contained so it does not require .NET to be installed.

**Comment by DougHennig** [comment]
1. Newer assemblies require deploying several more DLLs and I want to keep this as small as possible. Also, the signature for some methods has changed and requires significant changes to the wrapper program.
2. Creating a self-contained application would make SFMail significantly larger to deploy and again I want to keep this as small as possible.

Feel free to fork this repository and make these changes in your fork.
