### ISSUE TITLE
Cannot run from network share

### ISSUE THREAD

**Issue by kobruleht** [DougHennig/SFMail#6]
Using it from application in network share is not possible.
It throws error

> An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. 
> This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. 
> If this load is not intended to  sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.comifwlink/?LinkId=155569 for more information.
>

**Comment by DougHennig** [comment]
You need a config file. See the note in the README.md section under "Using SFMail".
