### ISSUE TITLE
Error OLE IDispatch exception code 0 from MailKit: 535: Incorrect authentication data.."

### ISSUE THREAD

**Issue by flexsoluciones** [DougHennig/SFMail#7]
error OLE IDispatch exception code 0 from MailKit: 535: Incorrect authentication data..", run in form vfp

port user and password correct ?

in main prg 

SET PROCEDURE TO sfmail.prg

**Comment by DougHennig** [comment]
You have to make sure all of the settings are correct: cServer, cUser, cPassword, nSecurityOptions, etc.

**Comment by flexsoluciones** [comment]
yes ,It may be that attachments don't exist in some cases

**Comment by DougHennig** [comment]
The error message sounds more like the settings are not correct.

**Comment by flexsoluciones** [comment]
try IF !EMPTY(fileridesri) AND !EMPTY(filerespsri)
   .cAttachments = &fileridesri + ',' + &filerespsri
ENDIF

**Comment by DougHennig** [comment]
The error message is "Incorrect authentication data". It does not say anything about attachments. Can you send an email without an attachment or does that fail too?

**Comment by DougHennig** [comment]
Closing this for lack of response. Feel free to reopen it if necessary.
