### ISSUE TITLE
About sending a second time

### ISSUE THREAD

**Issue by jhernancanom** [DougHennig/SFMail#8]
## 📝 Provide detailed reproduction steps (if any)

1. I have a form to send emails; it is responsible for (1) getting a message (I provide an standard form), (2) getting several files attached, and the TO and CC email addresses. The attached files I provide hace an specific name for every customer, based on his own code or identification.
2. It sends the message fine, with or without attached files.
3. My problem is when we need to send a second time the same files to the same customer. I need to erase the previous created files --before creating it again--, but I am receiving "Access denied", as if it was opened by the previous sending.

### ✔️ Expected result

I need to erase the file generated in a sending previous to the current.

### ❌ Actual result

I receive the error message "Access denied", but we must understand that I do not open the file I am going to attach: I only create it and attach it to the SFMail message.
When I go to see the received message (the first), I can download/see the attached file.

### What I have tried

I have put one sentence for clean the .cAttachments property (as we can see in the attached image), but it does not help: nor (1) using an empty space, nor (2) using null. Besides, I have put 
`loMail = null`
to try to clean the entire object.... but it does nothing (the error still appears).

How should I free the files attached in one sending, for I can send them in a post sending --immediatelly or not--?

## 📷 Screenshots
![image](https://github.com/DougHennig/SFMail/assets/5818845/069a9bd7-cb9a-4a0e-8010-eed200f72a10)

**Comment by DougHennig** [comment]
What is the datetime for SMTPLibrary2.dll?

**Comment by jhernancanom** [comment]
Dic-03-2020.
Veo que hay una actualziada con fecha **Ene-2023**. Intentaré con ésa.
![image](https://github.com/DougHennig/SFMail/assets/5818845/6711f43a-8a7e-4547-abe2-0f6bfb29bb24)
![image](https://github.com/DougHennig/SFMail/assets/5818845/96b7da4d-0ffa-466b-a7d2-984a666f3b3d)

**Comment by DougHennig** [comment]
That is an old version. Download the latest version from here and try again.

**Comment by jhernancanom** [comment]
Yes.
Thanks.
