### ISSUE TITLE
send attach files  error file not open

### ISSUE THREAD

**Issue by flexsoluciones** [DougHennig/SFMail#9]
y try send files scan 
send return t 
mensagge file not open
endscan 

![image](https://github.com/DougHennig/SFMail/assets/97065807/61c6cd28-4e82-4ed2-ac72-e64ab4aa5650)

**Comment by DougHennig** [comment]
What line of code is executing when the error occurs?

**Comment by mmslaty** [comment]
Hello sir..
![image](https://github.com/user-attachments/assets/0eea27cb-3a12-4065-a939-6a6996f57881)
This is what I have seen after running your apps..
could you please help me resolve this issue.
regards

**Comment by DougHennig** [comment]
The error message is telling you the problem: authentication was unsuccessful. That means the user name or password are incorrect.

**Comment by mmslaty** [comment]
thank sir for your fast replay
but I am sure my username and password are correct!!
regards

**Comment by DougHennig** [comment]
Set the cLogFile property to the name of a text file such as EmailLog.txt. Run the code again, then look at the content of EmailLog.txt. It may give you more information about the problem.

**Comment by mmslaty** [comment]
Sir..
thank you very much for Your guidance I  followed them and text attached is what I get
[smfllog.txt](https://github.com/user-attachments/files/17324731/smfllog.txt)
So I need your help sir could you please check with me..
regards

**Comment by DougHennig** [comment]
Unfortunately, I do not know enough about email systems to figure out the problem.

**Comment by mmslaty** [comment]
thank you Sir very much..
I truly appreciate all your help,,
Best regards
